/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThemePreviewRouteImport } from './routes/theme-preview'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as ApiPublicRobotsRouteImport } from './routes/api/public/robots'
import { Route as ApiPublicSitemapRouteImport } from './routes/api/public/sitemap'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemePreviewRoute = ThemePreviewRouteImport.update({
  id: '/theme-preview',
  path: '/theme-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRobotsRoute = ApiPublicRobotsRouteImport.update({
  id: '/api/public/robots',
  path: '/api/public/robots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSitemapRoute = ApiPublicSitemapRouteImport.update({
  id: '/api/public/sitemap',
  path: '/api/public/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/theme-preview': typeof ThemePreviewRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/robots': typeof ApiPublicRobotsRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/theme-preview': typeof ThemePreviewRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/robots': typeof ApiPublicRobotsRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/theme-preview': typeof ThemePreviewRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/robots': typeof ApiPublicRobotsRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/theme-preview'
    | '/api/public/contact'
    | '/api/public/robots'
    | '/api/public/sitemap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/theme-preview'
    | '/api/public/contact'
    | '/api/public/robots'
    | '/api/public/sitemap'
  id:
    | '__root__'
    | '/'
    | '/theme-preview'
    | '/api/public/contact'
    | '/api/public/robots'
    | '/api/public/sitemap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThemePreviewRoute: typeof ThemePreviewRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiPublicRobotsRoute: typeof ApiPublicRobotsRoute
  ApiPublicSitemapRoute: typeof ApiPublicSitemapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theme-preview': {
      id: '/theme-preview'
      path: '/theme-preview'
      fullPath: '/theme-preview'
      preLoaderRoute: typeof ThemePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/robots': {
      id: '/api/public/robots'
      path: '/api/public/robots'
      fullPath: '/api/public/robots'
      preLoaderRoute: typeof ApiPublicRobotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sitemap': {
      id: '/api/public/sitemap'
      path: '/api/public/sitemap'
      fullPath: '/api/public/sitemap'
      preLoaderRoute: typeof ApiPublicSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThemePreviewRoute: ThemePreviewRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiPublicRobotsRoute: ApiPublicRobotsRoute,
  ApiPublicSitemapRoute: ApiPublicSitemapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
